### ISSUE TITLE
home-page

### ISSUE THREAD

**Issue by surajsingla333** [buidl-labs/zombies-in-the-room#35]
**What's the motivation behind the feature? what problem does the feature intend to solve ?**
The current home page (landing page) is a 'Start Learning' button. This feature will update the home page as per [this ](https://www.figma.com/proto/hcoRbRF5fZREDTJkLl7cXk/BUIDL-for-Tezos?node-id=1%3A2&scaling=scale-down-width) design.

**Describe the solution you'd like.**
A responsive landing page using flexbox and grids.

**Comment by bhaskarSingh** [comment]
The reason behind why I emphasis on the following features template, is to understand your approach before execution, to help you from getting lost mid solution.

The following is how I would approach the implementation of the home page:

This is not a trivial task and will not be clear at first, take your time and experiment to have full clarity on execution in pseudo code, for whenever working on a feature or implementation for which execution path is unknown or that requires breaking the logic into multiple separate steps.

**1. Communicate overall strategy**
Using the CSS grid-system to divide the pages into main-body and footer containers, designing the layout mobile-first and then making it responsive for table and desktop viewport view.

**2. Pseudo Code(Can I implement the logic from your explanation)**


    - Slightly more specific than step 1
    - Should focus on main pieces
    - Helps you to not get lost mid solution
    - Communicate line by line
        - A solid and concise explanation
        - A consistent method of explanation
        - Opportunity to explain why and how the code is working

For the Mobile view
```javascript
// create a grid container for main-body and footer using grid-area property
  //inside main-body conatiner
    //create three sperate divs which is wrapped by flex-div parent container, set justify-content and align-content property to the center for aligning content to the center of the page vertically and horizontally.
      /*1) for plants and zombies logo image
      2)for hero text 
      3)for start-learning click to action button(hide:  plant & zombie image for mobile view) */
     //load all the images using gatsby plugin which provides responsive image sizes according to the viewport automatically
    //Footer implementation to be executed later when the design is finalized
```

For Table and Desktop viewport view
// add media-query with min-width: 768px 
      //to show plant and zombie images back
// Other than that logic will remain the same


```javascript
<!-- Structure break down -->
<GridContainer>
<Main>
 <FlexContainer>
         <plants-vs-zombies image>
         <hero text conatiner>
              <ttitle/>
              <subheading/>
          <hero text conatiner>
          <div>
               <plant image/>
               <start learning-click-to-action-button> 
               <zombie image/>
          <div>
 <FlexContainer>
</Main>
<Footer>
</Footer>
</GridConatiner>
```

**3. Communicate if you don’t know something/hit a block**

    - What is the problem
    - What did I expect to happen
    - What I have tried
    - Why I expect it’s not working

Nothing as of right now

**5. Optional Summary Explanation**
> Perfect if line by line pseudo code isn't clear

The above logic is clear enough

**Describe alternatives you've considered**
> A clear and concise description of any alternative solutions or features you've considered.

None

**Additional context**
>Add any other context or screenshots about the feature here if any.

None
