### ISSUE TITLE
Play shooting game at end of lesson

### ISSUE THREAD

**Issue by dhruv10** [buidl-labs/zombies-in-the-room#43]
**Roadmap for game implementation:**

Using a tabular structure since defined steps need to be followed for the gamification part. For any bugs/ features related specificly to the game please write another comment in this issue itself.

| S.No. | Procedure | Description | Result | ETA | Delivered Time |
| :--- | :--- | :--- | :--- | :--- |  :--- |
| 1. | Research on implementation methods | Study various methods of implementing this game and figure out the best method. | I see two methods that can benefit us: 1. Using DOM directly for making the game (lightweight, easier to implement). 2. Using Canvas (for better support of animations, comparatively difficult). We need to run a pilot to finalize what fits best for us. | 8/04/2020 | 8/04/2020 |
| 2. | Running pilot in a separate repo | First try Method 1 (described above) and stick to it if it fulfills the requirement and move to Method 2 if it doesn't. The outcome is to finalize a Method that suits us best. | Finalized Method 1, pilot deployed [here](http://orange-horn.surge.sh/) | 9/04/2020 9 PM | 9/04/2020 9 PM |
| 3. | Adding sprite animations & correcting the aesthetics | Added sprite animations using steps method in CSS and corrected the aesthetics | Outcome deployed [here](https://orange-horn.surge.sh), feedback awaited | 10/04/2020 9 PM | 10/04/2020 9 PM |
| 4. | Implement onboarding animations and integration with the main repo |  | Integrated with the main repo, the team decided to move characters into separate components so putting the before adding animation | 12/04/2020 9 PM | 13/04/2020 10 PM |
| 5. | Using Plant as a combo of separate components |  |  | 15/04/2020 12 AM | |
| 5. | Onboarding animations |  |  | 15/04/2020 9 PM | |

**Comment by bhaskarSingh** [comment]
just wanted to mention that if the plant animation is created using sprites then we would require to change it to moving SVG parts since we are going to integrate randomly generated plant type into the game

**Comment by dhruv10** [comment]
> just wanted to mention that if the plant animation is created using sprites then we would require to change it to moving SVG parts since we are going to integrate randomly generated plant type into the game

Got it.
