### ISSUE TITLE
UI Fixes/Suggestions

### ISSUE THREAD

**Issue by AbhinavThukral97** [buidl-labs/zombies-in-the-room#61]
Describing brief pointers for fixing some UI elements.

Landing Page:
- The logo needs to be smaller in height
- Fixing the uneven spacings and proportions of the graphics
- Increasing the speed of the cloud animation
- Start now button fix (padding needs to be less, spacing between the text and icon needs to be increased, hover effect suggestion: `box-shadow: 0 0 0 0.25rem rgba(41,203,106,0.2);`)
- Footer padding to be increased from the top, footer font size to be decreased.

Chapters View: 
- "Back" button needs to be spaced from the corners of the window/media
- Spacing between the chapter lists to be decreased, line separators can be thinned to probably 1px or 2px
- Size of the seed to be increased
- Width of the story text to be 80% of the container
- Footer component to be added

Learning Interface:
- `outline: none` for all buttons (referring to the back button)
- Icons to be replaced by the svg icons on figma
- Horizontal padding of the code interface buttons (and tabs) to be increased
- Font size of the chapters overlay menu can be decreased

Completion View:
- Proportions of the generated plant (needs a bigger head, front and back leaves should be the same)
- Font weight of Success in all views to be thin (300/400)
- Footer background colour to be matched with the design
- Battle it out to have the same hover effect/styling as all the filled buttons (eg. start now on the landing)

**Comment by dhruv10** [comment]
Suggestion: These points can be changed to `checklist type` so that these can marked done by @AbhinavThukral97 after verification. This helps in tracking each point separately.

**Comment by bhaskarSingh** [comment]
> Footer background colour to be matched with the design

it should match the background color or the current figma designed footer footer background color ?

**Comment by AbhinavThukral97** [comment]
> > Footer background colour to be matched with the design
> 
> it should match the background color or the current figma designed footer footer background color ?

Footer Background from Figma

**Comment by bhaskarSingh** [comment]
> Icons to be replaced by the svg icons on figma

this issue is being handled separately in #51
